---
- name: Create Users
  hosts: target-machines
  become: yes
  vars:
    users_to_create:
      - { name: isaya, group: group1, password: password1, home: /home/isaya }
      - { name: noble, group: group2, password: password2, home: /home/noble }
      - { name: mutuwa, group: group3, password: password3, home: /home/mutuwa }
  roles:
    - add-users
