---
- name: Create Users
  hosts: target-machines
  become: yes
  vars:
    users_to_create:
      - { name: isaya, group: Backend, password: password1, home: /home/isaya }
      - { name: noble, group: DevOps, password: password2, home: /home/noble }
      - { name: mutuwa, group: Frontend, password: password3, home: /home/mutuwa }
  roles:
    - add-users
